### PR TITLE
Julia v1.3 compatibility

### PR DESCRIPTION
**Pull request by wakakusa**
compatible with Julia v1.0 &1.3 and LightGBM v2.3.1 and modified test.jl to work with Julia v1.0 &v1.3.

### CODE REVIEW

**Comment by wakakusa** [comment]
Compatible with Julia v1.2 and LightGBM v2.3.0. test.jl also supports Julia v1.2.

**Comment by Allardvm** [comment]
@wakakusa I must say that your contributions and persistence continue to impress me. Since I will not be in a position to provide meaningful substantive contributions in the immediate future, I'm wondering if you would be willing to consider full ownership of the package?

**Comment by wakakusa** [comment]
@Allardvm  Thank you for contacting me. I have limited time to work on this package, but I would like to contribute as much as possible.

**Comment by ValdarT** [comment]
Regarding ownership, perhaps it would be best to try to move it to the official repo like the R and Python packages once it's working well on Julia v1.x?

**Comment by Allardvm** [comment]
Sounds like a plan! @wakakusa, could you give me a heads-up when you feel this in a good state for a review?

**Comment by wakakusa** [comment]
@Allardvm, I made Julia v 1.0 & 1.3 compatible with LightGBM v 2.3. 1 and test.jl did not show any errors. The README.md contains a link to a web site describing the function. If you are okay with this condition, please review it. If it is unnecessary, I will delete it and contact you.

**Comment by wakakusa** [comment]
@Allardvm ,Removed links to Web sites that describe functions in the README.md. I wrote Julia v 1.0 & 1.3 in LightGBM v 2.3 .1 and test.jl had no errors. Please review it.

**Comment by azev77** [comment]
@Allardvm @wakakusa thanks for updating this to work w/ Julia 1.x!
It would be awesome if it was moved to the official repo like R/Python. 
It would be also great if there was a wrapper to [MLJ](https://github.com/alan-turing-institute/MLJ.jl).jl

**Comment by wakakusa** [comment]
@Allardvm  @azev77 
I have three ideas about how to proceed with package development.
Which do you think we should start with?

Suggestion 1: Create official Julia package
Summary: Allow Julia official package manager to install
Challenge: Where is the repository to register with the official Julia package?
I don't know what the process will be if you merge it into LightGBM like Python or R, so I need to know.

Proposal 2: LightGBM C Language API Wrapper Added
Overview: Adding API Wrappers
Issue: Which API wrappers should I add from? Is it okay to follow the order in the manual?

Proposed 3. Create a wrapper around MLJ.jl
Summary: Create a Wrapper for MLJ.jl
Problem: I've never used MLJ.jl, so I need to learn how to use it first.

**Comment by azev77** [comment]
@wakakusa are you aware of: https://github.com/IQVIA-ML/LightGBM.jl
It already has an MLJ interface (just an additional script)
There is [discussion ](https://github.com/alan-turing-institute/MLJModels.jl/issues/227)about making LightGBM easier to install.  

Is it possible to somehow join forces?

**Comment by yalwan-iqvia** [comment]
> @wakakusa I must say that your contributions and persistence continue to impress me. Since I will not be in a position to provide meaningful substantive contributions in the immediate future, I'm wondering if you would be willing to consider full ownership of the package?

Hello all -- I'm sorry that I only just noticed this activity.

I had already taken the liberty of registering https://github.com/IQVIA-ML/LightGBM.jl into the julia general registry. We had been working with Alan Turing team to get the MLJ interface operational, and have been working with this with the intention of taking over the maintenance responsibility.

@wakakusa my apologies, I tried to reach you via an e-mail associated to your git commits but I received no response. I realise as well that this was not transparent because most of the initial development was conducted in private. However, I am happy to share maintenance responsibilities if that is something you wish for.

> Suggestion 1: Create official Julia package

This is an idea we had as well, although its not high up on the list for us. However we do intend to engage with Microsoft so we can find out what it would take for the Julia package to become part of their actual repo. As of so far, they seem ok with external unofficial packages binding to the library, however.

@Allardvm since we have registered the package and intend to keep it up-to-date are you happy for us to become de-facto maintainers?

The repository is here https://github.com/IQVIA-ML/LightGBM.jl as @azev77 pointed out, and we could continue a discussion there.

**Comment by wakakusa** [comment]
@yalwan-iqvia You sent me an email, but I didn't receive it. Why?

The main part I maintained was to download the LightGBM libraries from the official LightGBM site and automatically set the environment path if the LightGBM libraries were not installed in the execution environment. I have confirmed with TravisCI that it runs on macOS and Linux.

Since the repository you are maintaining is actively being developed, why not add the download process for my maintained LightGBM library, which seems to be not currently implemented, and make your repository the main one?

@Allardvm I would like to ask them for maintenance. What do you think?

**Comment by yalwan-iqvia** [comment]
hi @wakakusa 

Sorry that the e-mail did not reach you. It must have gone to your spam folder. However, I sent it in January, so I don't think you'd be able to retrieve it now.

As for automatically downloading the binary, please see this commit: https://github.com/IQVIA-ML/LightGBM.jl/commit/b5293367b451b9a8fcd78d055890a384bc8c2485
It is a basic mechanism but it seems to work in majority of cases. Please give it a try and let me know if it works or not.

**Comment by wakakusa** [comment]
@yalwan-iqvia
I tried that you told me. I confirmed that it works without any problem. I am sorry if my misunderstanding made you feel bad.

**Comment by yalwan-iqvia** [comment]
@wakakusa not at all, thank you for testing. 

Please feel free to contribute or raise issues against the repo.

**Comment by yalwan-iqvia** [comment]
@Allardvm @wakakusa 

I have asked LightGBM team if they would update link on readme to point at our repo. However they would like to hear from you directly as well: https://github.com/microsoft/LightGBM/issues/3008

**Comment by Allardvm** [comment]
@yalwan-iqvia Thanks a million for your efforts. Yes, you're more than welcome to take ownership of the package and reuse and redistribute any of the code as you see fit. Feel free to redirect any references to this repository to your own.

If your package is ready, I could add a link to your repository to the readme and archive this repository.

**Comment by yalwan-iqvia** [comment]
@Allardvm Thanks for getting back to us.

I would say our version of the package is ready in the sense that it is registered in general registry and we have plans to continue actively developing in response to requests and for our needs. If you find this satisfactory then please go ahead with actions for this repository.

You will always be listed as original author of this package and if you wish to come back to maintenance responsibilities you need only request that on our repository and we will be happy to make arrangements for this case.

**Comment by wakakusa** [comment]
@yalwan-iqvia  Thank you.
The time to work on the package is limited. I will continue to cooperate with the development of this package, so I will be very happy if you are the main maintainer and continue the maintenance and development.

When the LightGBM readme is updated, I will also archive my repository.

**Comment by Allardvm** [comment]
Closing this in favour of the new (and maintained) repository located here: https://github.com/IQVIA-ML/LightGBM.jl .

**Pull request closed without merging**
